sudo: false
language: python
python:
  - 2.7
  - 3.4
  - pypy
  - pypy3
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
script:
  - python -m pytest --cov=SensorMonitor
after_success:
  - coveralls
